name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    branches:
    - main
jobs:
  run-test:
    runs-on: self-hosted
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ready')
    steps:
      - name: my-step
        run: echo "Hello World!
