name: trigger-CI
run-name: ${{ github.actor }} is Trigerring CI
on:
  issue_comment:
    types: [created]
jobs:
  run-test:
    runs-on: self-hosted
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ready')
    steps:
      - name: my-step
        run: echo "Hello World!"
